# harness-kit — Makefile (harness-kit, stack-agnostic skeleton)
# Generated by harness-kit v1, then bootstrapped for THIS project (Node CLI).
#
# This Makefile wraps the project's npm scripts so that the harness contract
# (`make setup / test / lint / typecheck / build / check / clean`) is the
# single canonical entry point used by docs, CI, and agents.

.PHONY: help \
        setup dev test e2e lint typecheck build check clean

help:
	@echo "harness-kit — common targets:"
	@echo ""
	@echo "  make setup         install dependencies (npm install)"
	@echo "  make dev           tsup watch mode"
	@echo "  make test          vitest run"
	@echo "  make e2e           bash scripts/e2e-check.sh"
	@echo "  make lint          biome check ."
	@echo "  make typecheck     tsc --noEmit"
	@echo "  make build         tsup (build dist/cli.cjs)"
	@echo "  make check         lint + typecheck + test + build"
	@echo "  make clean         remove build artifacts"
	@echo ""
	@echo "Harness scripts (not Make targets — bash directly):"
	@echo "  bash scripts/session-init.sh           L06 briefing"
	@echo "  bash scripts/exit-clean.sh             L12 5-dim end-of-session check"
	@echo "  bash scripts/validate-feature.sh <id>  run a feature's verification"
	@echo "  cat  .harness/bootstrap-prompt.txt     re-read the bootstrap prompt"
	@echo ""
	@echo "Or use the harness CLI directly:"
	@echo "  harness doctor     score the harness (5 subsystems + cold-start)"

# --- Project-specific targets (real commands for harness-kit itself) ---

setup:
	@npm install

dev:
	@npm run dev

test:
	@npm test

e2e:
	@bash scripts/e2e-check.sh

lint:
	@npm run lint

typecheck:
	@npm run typecheck

build:
	@npm run build

check: lint typecheck test build
	@echo "✓ check passed"

clean:
	@rm -rf dist .cache .tmp coverage 2>/dev/null || true
