# ${PROJECT_NAME} — Agents Entry Point

> Single entry point for all coding agents (${AGENT_LIST}).
> This file is intentionally short. It routes to deeper docs on demand.
> Generated by [harness-kit](https://github.com/Bojun-Vvibe/harness-kit) v${TEMPLATE_VERSION}.
> harness-kit packages [walkinglabs/learn-harness-engineering](https://github.com/walkinglabs/learn-harness-engineering).

## What this is

> **TODO**: one or two sentences describing this project — what it does, who it's for, what stack/runtime it runs on.

## Quick start

```bash
make setup     # install dependencies
make test      # run tests
make check     # lint + typecheck + tests + build (the full bar)
```

## Hard rules (read before editing anything)

- See [`CONSTRAINTS.md`](./CONSTRAINTS.md) — non-negotiable rules. Violating these breaks the build.
- WIP = 1. Only one feature in `features.json` may be in state `active` at a time. (L07)
- A feature is **done** only when its `verification` command exits 0. Not "code looks ok". (L09)
- Do not modify `features.json` state by hand — use `harness feature start|done|block`.
- Before declaring victory, run `make check` AND `harness feature done <id>`. Both must pass.

## Deeper docs (read on demand)

- [`docs/architecture.md`](./docs/architecture.md) — system structure, layer boundaries
- [`docs/decisions.md`](./docs/decisions.md) — ADR log; why things are the way they are
- [`docs/testing-standards.md`](./docs/testing-standards.md) — what counts as a real test
- [`docs/templates/sprint-contract.md`](./docs/templates/sprint-contract.md) — for multi-step work
- [`docs/templates/rubric.md`](./docs/templates/rubric.md) — review evaluation rubric

## State (read this every session)

- [`PROGRESS.md`](./PROGRESS.md) — what the last session did, what's blocked, what's next
- [`features.json`](./features.json) — the spine: every feature with its verification command
- [`QUALITY.md`](./QUALITY.md) — per-module quality grade, where to focus next

## Session protocol

**At the start of every session:**

```bash
harness session start
```

This reads `PROGRESS.md`, sanity-checks tooling, and prints a briefing.

**At the end of every session:**

```bash
harness session end "what I did this session"
```

This stamps `PROGRESS.md` and runs the 5-dimension exit-clean check (L12).
**Do not consider the session complete until exit-clean passes.**

## When in doubt

```bash
harness doctor    # 5-subsystem health score + cold-start test
harness feature list
make check
```
